name: "Fusuma Updater"
on:
  workflow_dispatch:
  
env:
  NIXPKGS_REPO: "LazyGeniusMan/nixpkgs"
  NIXPKGS_BRANCH: "master"
  NIXPKGS_NAME: "fusuma"
  NIXPKGS_VER_OLD: "1.3.0"
  NIXPKGS_VER_NEW: "2.4.1"
  NIXPKGS_DIR: "./pkgs/tools/inputmethods/fusuma"

jobs:
  nixpkgs-fusuma-updater:
    name: Fusuma Updater
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        repository: ${{ env.NIXPKGS_REPO }}
        ref: ${{ env.NIXPKGS_BRANCH }}
        fetch-depth: 1
    - name: Update
      run: |
        cd ${{ env.NIXPKGS_DIR }}
        nix-shell -p ruby bundix --run "bundler update"
        nix-shell -p ruby bundix --run "bundix -l"
    - name: Upload nixpkgs source
      uses: actions/upload-artifact@v3.1.0
      with:
        name: nixpkgs-source-${{ env.NIXPKGS_NAME }}-${{ env.NIXPKGS_VER_NEW }}-${{ github.run_id }}
        path: |
          ${{ env.NIXPKGS_DIR }}/Gemfile
          ${{ env.NIXPKGS_DIR }}/Gemfile.lock
          ${{ env.NIXPKGS_DIR }}/gemset.nix
          ${{ env.NIXPKGS_DIR }}/default.nix
    - name: Commit to new branch
      uses: EndBug/add-and-commit@v9.1.0
      with:
        author_name: ${{ secrets.GIT_NAME }}
        author_email: ${{ secrets.GIT_EMAIL }}
        committer_name: ${{ secrets.GIT_NAME }}
        committer_email: ${{ secrets.GIT_EMAIL }}
        message: "${{ env.NIXPKGS_NAME }}: ${{ env.NIXPKGS_VER_OLD }} -> ${{ env.NIXPKGS_VER_NEW }}"
        new_branch: ${{ env.NIXPKGS_NAME }}-${{ env.NIXPKGS_VER_NEW }}-${{ github.run_id }}
        github_token: ${{ secrets.PAT }}
